import type { HardwareProfileTier } from './hardwareProfileTiers'

/**
 * Static model catalog entry, independent of any runtime hardware detection.
 * `recommendedForProfiles` replaces the old inline `isRecommended: profileTier === 'x'`
 * conditionals — the catalog itself no longer needs to know about `profileTier` at
 * all, so each tier below is plain data instead of a function body (see AGT6:
 * analyzeHardwareAndRecommend in hardwareRecommendationEngine.ts used to embed all
 * of this directly, ~700 lines in a single function).
 *
 * INVARIANT (enforced by hardwareRecommendationEngine.test.ts): a model may only be
 * listed in `recommendedForProfiles` for a profile whose safe VRAM/RAM budget can
 * actually host it — `assessModelHardwareCompatibility` must not return
 * `exceeds_vram` for that pairing. The wizard pre-selects these entries, so an
 * over-ambitious recommendation used to hand minimum-spec and even 24GB machines a
 * default model the engine itself flagged as an OOM risk.
 */
export interface RawModelCatalogEntry {
  modelName: string
  displayName: string
  family: string
  sizeBytesApprox: string
  description: string
  recommendedForProfiles: HardwareProfileTier[]
}

// 🟢 Compact coding models (0.5B - 4B) — the only ones that fit legacy / CPU-only hosts.
export const COMPACT_CODING_CATALOG: RawModelCatalogEntry[] = [
  {
    modelName: 'qwen2.5-coder:1.5b',
    displayName: 'Qwen 2.5 Coder (1.5B)',
    family: 'qwen-coder',
    sizeBytesApprox: '1.1 GB',
    description: 'Ultra-fast code completion with minimal memory footprint & rapid token response',
    recommendedForProfiles: ['legacy', 'entry', 'midrange'],
  },
  {
    modelName: 'qwen2.5-coder:1.5b-instruct-q8_0',
    displayName: 'Qwen 2.5 Coder (1.5B Q8_0)',
    family: 'qwen-coder',
    sizeBytesApprox: '1.6 GB',
    description: 'High-precision 8-bit quantized fast coding model',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5-coder:3b',
    displayName: 'Qwen 2.5 Coder (3B)',
    family: 'qwen-coder',
    sizeBytesApprox: '1.9 GB',
    description: 'Compact high-accuracy code assistant for rapid editing & small refactors',
    recommendedForProfiles: ['highend', 'extreme'],
  },
  {
    modelName: 'qwen2.5-coder:3b-instruct-q4_k_m',
    displayName: 'Qwen 2.5 Coder (3B Q4_K_M)',
    family: 'qwen-coder',
    sizeBytesApprox: '1.8 GB',
    description: 'Quantized compact code assistant for fast edits',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5-coder:0.5b',
    displayName: 'Qwen 2.5 Coder (0.5B)',
    family: 'qwen-coder',
    sizeBytesApprox: '400 MB',
    description: 'Ultra-compact micro model for background helper tasks & zero memory pressure',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:1.7b',
    displayName: 'Qwen 3 (1.7B)',
    family: 'qwen',
    sizeBytesApprox: '1.4 GB',
    description: 'Current-generation compact instruct model with native tool calling and toggleable thinking',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:0.6b',
    displayName: 'Qwen 3 (0.6B)',
    family: 'qwen',
    sizeBytesApprox: '520 MB',
    description: 'Smallest current-generation model for routing and helper turns on minimum hardware',
    recommendedForProfiles: [],
  },
  {
    modelName: 'granite3.3:2b',
    displayName: 'IBM Granite 3.3 (2B)',
    family: 'granite',
    sizeBytesApprox: '1.5 GB',
    description: 'IBM compact enterprise model with reliable structured JSON and tool-call output',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gemma3:1b',
    displayName: 'Google Gemma 3 (1B)',
    family: 'gemma',
    sizeBytesApprox: '820 MB',
    description: 'Google ultra-light model for conceptual lookups on CPU-only and low-RAM systems',
    recommendedForProfiles: [],
  },
  {
    modelName: 'llama3.2:1b',
    displayName: 'Llama 3.2 (1B)',
    family: 'llama',
    sizeBytesApprox: '1.3 GB',
    description: 'Minimal footprint model for ultra low-spec hardware and background helpers',
    recommendedForProfiles: [],
  },
  {
    modelName: 'llama3.2:3b',
    displayName: 'Llama 3.2 (3B)',
    family: 'llama',
    sizeBytesApprox: '2.0 GB',
    description: 'Balanced lightweight model for quick lookups, doc inspection & rapid editing',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5:1.5b',
    displayName: 'Qwen 2.5 (1.5B)',
    family: 'qwen',
    sizeBytesApprox: '1.0 GB',
    description: 'Fast Alibaba lightweight instruction model for concise task routing',
    recommendedForProfiles: [],
  },
  {
    modelName: 'codegemma:2b',
    displayName: 'Google CodeGemma (2B)',
    family: 'gemma',
    sizeBytesApprox: '1.4 GB',
    description: 'Google micro code-completion model for fill-in-the-middle on minimum hardware',
    recommendedForProfiles: [],
  },
]

// 🔵 Workhorse coding models (3B - 30B). This is the curated ladder: `recommendedForProfiles`
// here maps each hardware profile to its default coding model, and it is the ONLY catalog the
// single-model recommendation reads (see buildCodingModelCatalog in hardwareRecommendationEngine.ts).
export const WORKHORSE_CODING_CATALOG: RawModelCatalogEntry[] = [
  {
    modelName: 'qwen2.5-coder:7b',
    displayName: 'Qwen 2.5 Coder (7B)',
    family: 'qwen-coder',
    sizeBytesApprox: '4.7 GB',
    description: 'State-of-the-art coding workhorse with high JSON precision & tool calling support',
    recommendedForProfiles: ['midrange', 'highend'],
  },
  {
    modelName: 'qwen2.5-coder:7b-instruct-q4_k_m',
    displayName: 'Qwen 2.5 Coder (7B Q4_K_M)',
    family: 'qwen-coder',
    sizeBytesApprox: '4.4 GB',
    description: 'Quantized 7B coding workhorse offering optimal VRAM headroom on 8GB GPUs',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5-coder:7b-instruct-q5_k_m',
    displayName: 'Qwen 2.5 Coder (7B Q5_K_M)',
    family: 'qwen-coder',
    sizeBytesApprox: '5.1 GB',
    description: 'High-precision 5-bit quantized coding workhorse',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5-coder:3b',
    displayName: 'Qwen 2.5 Coder (3B)',
    family: 'qwen-coder',
    sizeBytesApprox: '1.9 GB',
    description: 'Balanced low-VRAM coding assistant preserving full headroom on 4-6GB GPUs or CPU',
    recommendedForProfiles: ['legacy', 'entry'],
  },
  {
    modelName: 'qwen3:4b',
    displayName: 'Qwen 3 (4B)',
    family: 'qwen',
    sizeBytesApprox: '2.6 GB',
    description: 'Current-generation 4B with native tool calling — best accuracy per GB on minimum hardware',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:8b',
    displayName: 'Qwen 3 (8B)',
    family: 'qwen',
    sizeBytesApprox: '5.2 GB',
    description: 'Current-generation 8B general/coding hybrid with strong multi-step tool use',
    recommendedForProfiles: [],
  },
  {
    modelName: 'granite3.3:8b',
    displayName: 'IBM Granite 3.3 (8B)',
    family: 'granite',
    sizeBytesApprox: '4.9 GB',
    description: 'IBM enterprise 8B model tuned for long-context RAG and disciplined tool calling',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5-coder:14b',
    displayName: 'Qwen 2.5 Coder (14B)',
    family: 'qwen-coder',
    sizeBytesApprox: '9.0 GB',
    description: 'Large-scale coding model for architectural refactoring and multi-file workflows',
    recommendedForProfiles: ['extreme'],
  },
  {
    modelName: 'qwen2.5-coder:14b-instruct-q4_k_m',
    displayName: 'Qwen 2.5 Coder (14B Q4_K_M)',
    family: 'qwen-coder',
    sizeBytesApprox: '8.9 GB',
    description: 'Quantized 14B coding model for high-end GPUs',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3-coder:30b',
    displayName: 'Qwen 3 Coder (30B A3B MoE)',
    family: 'qwen-coder',
    sizeBytesApprox: '18.6 GB',
    description: 'Mixture-of-Experts coding model: 30B knowledge at ~3B active-parameter inference speed',
    recommendedForProfiles: [],
  },
  {
    modelName: 'devstral:24b',
    displayName: 'Mistral Devstral (24B)',
    family: 'mistral',
    sizeBytesApprox: '14.0 GB',
    description: 'Mistral agentic coding model purpose-built for multi-file tool loops',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-coder:6.7b',
    displayName: 'DeepSeek Coder (6.7B)',
    family: 'deepseek',
    sizeBytesApprox: '3.8 GB',
    description: 'DeepSeek specialized code generation model with low VRAM requirement',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-coder:6.7b-instruct-q4_k_m',
    displayName: 'DeepSeek Coder (6.7B Q4_K_M)',
    family: 'deepseek',
    sizeBytesApprox: '3.8 GB',
    description: 'Quantized DeepSeek code model for reliable generation',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-coder-v2:16b-lite-instruct-q4_k_m',
    displayName: 'DeepSeek Coder V2 Lite (16B Q4_K_M)',
    family: 'deepseek',
    sizeBytesApprox: '8.9 GB',
    description: 'MoE coding architecture with 236 programming languages support',
    recommendedForProfiles: [],
  },
  {
    modelName: 'codestral:22b-v0.1-q4_k_m',
    displayName: 'Mistral Codestral (22B Q4_K_M)',
    family: 'mistral',
    sizeBytesApprox: '13.0 GB',
    description: 'Mistral enterprise code intelligence model (32k context)',
    recommendedForProfiles: [],
  },
  {
    modelName: 'codegemma:7b',
    displayName: 'Google CodeGemma (7B)',
    family: 'gemma',
    sizeBytesApprox: '5.0 GB',
    description: 'Google code-specialized model for fill-in-the-middle completion and generation',
    recommendedForProfiles: [],
  },
  {
    modelName: 'starcoder2:7b',
    displayName: 'StarCoder 2 (7B)',
    family: 'starcoder',
    sizeBytesApprox: '4.4 GB',
    description: 'BigCode open-access code generation assistant',
    recommendedForProfiles: [],
  },
  {
    modelName: 'codellama:7b-instruct-q4_k_m',
    displayName: 'Code Llama (7B Q4_K_M)',
    family: 'codellama',
    sizeBytesApprox: '4.0 GB',
    description: 'Meta Code Llama specialized Python & C++ model',
    recommendedForProfiles: [],
  },
  {
    modelName: 'llama3.2:3b',
    displayName: 'Llama 3.2 (3B)',
    family: 'llama',
    sizeBytesApprox: '2.0 GB',
    description: 'Balanced low-memory fallback model for CPU/Legacy systems',
    recommendedForProfiles: [],
  },
  {
    modelName: 'starcoder2:15b',
    displayName: 'StarCoder 2 (15B)',
    family: 'starcoder',
    sizeBytesApprox: '9.4 GB',
    description: 'BigCode large-scale code generation assistant for 12GB+ GPUs',
    recommendedForProfiles: [],
  },
  {
    modelName: 'codellama:13b-instruct-q4_k_m',
    displayName: 'Code Llama (13B Q4_K_M)',
    family: 'codellama',
    sizeBytesApprox: '7.4 GB',
    description: 'Meta larger Code Llama for Python & C++ on 12GB+ GPUs',
    recommendedForProfiles: [],
  },
]

// 🟣 Reasoning-oriented coding models (multi-step reasoning & architecture work).
export const REASONING_CODING_CATALOG: RawModelCatalogEntry[] = [
  {
    modelName: 'qwen2.5-coder:7b',
    displayName: 'Qwen 2.5 Coder (7B)',
    family: 'qwen-coder',
    sizeBytesApprox: '4.7 GB',
    description: 'High-capability coding assistant for deep logic, multi-step refactors & debugging',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:4b',
    displayName: 'Qwen 3 (4B)',
    family: 'qwen',
    sizeBytesApprox: '2.6 GB',
    description: 'Reasoning-capable 4B that fits a CPU-only or 4-6GB GPU budget — deep tier for minimum hardware',
    recommendedForProfiles: ['legacy', 'entry'],
  },
  {
    modelName: 'qwen3:8b',
    displayName: 'Qwen 3 (8B)',
    family: 'qwen',
    sizeBytesApprox: '5.2 GB',
    description: 'Current-generation 8B reasoning model for stack-trace analysis on 8GB GPUs',
    recommendedForProfiles: ['midrange'],
  },
  {
    modelName: 'qwen3:14b',
    displayName: 'Qwen 3 (14B)',
    family: 'qwen',
    sizeBytesApprox: '9.3 GB',
    description: 'Current-generation 14B reasoning engine for multi-file architecture work on 12GB+ GPUs',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-r1:7b',
    displayName: 'DeepSeek R1 Distill Qwen (7B)',
    family: 'deepseek-r1',
    sizeBytesApprox: '4.7 GB',
    description: 'Qwen 2.5-Coder/Math distilled reasoning model for deep algorithmic problem solving',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-r1:7b-qwen-distill-q4_k_m',
    displayName: 'DeepSeek R1 Distill Qwen (7B Q4_K_M)',
    family: 'deepseek-r1',
    sizeBytesApprox: '4.4 GB',
    description: 'Quantized Qwen-distilled reasoning model with low VRAM footprint',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-r1:1.5b',
    displayName: 'DeepSeek R1 Distill Qwen (1.5B)',
    family: 'deepseek-r1',
    sizeBytesApprox: '1.1 GB',
    description: 'Smallest distilled reasoning model — last-resort deep tier for CPU-only hosts',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5-coder:14b',
    displayName: 'Qwen 2.5 Coder (14B)',
    family: 'qwen-coder',
    sizeBytesApprox: '9.0 GB',
    description: 'Large-scale code intelligence for multi-file architecture refactors',
    recommendedForProfiles: ['highend'],
  },
  {
    modelName: 'deepseek-r1:14b',
    displayName: 'DeepSeek R1 Distill Qwen (14B)',
    family: 'deepseek-r1',
    sizeBytesApprox: '9.2 GB',
    description: 'High-capacity 14B Qwen-distilled reasoning engine for complex system design',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-r1:14b-qwen-distill-q4_k_m',
    displayName: 'DeepSeek R1 Distill Qwen (14B Q4_K_M)',
    family: 'deepseek-r1',
    sizeBytesApprox: '9.0 GB',
    description: 'Quantized 14B deep reasoning engine for 12GB+ GPUs',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gpt-oss:20b',
    displayName: 'GPT-OSS (20B)',
    family: 'gpt-oss',
    sizeBytesApprox: '13.5 GB',
    description: 'Open-weight reasoning model with adjustable effort and native tool use — fits a 24GB safe budget',
    recommendedForProfiles: ['extreme'],
  },
  {
    modelName: 'qwen3-coder:30b',
    displayName: 'Qwen 3 Coder (30B A3B MoE)',
    family: 'qwen-coder',
    sizeBytesApprox: '18.6 GB',
    description: 'MoE coding specialist for exhaustive repository-wide reasoning at 3B active-parameter speed',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5-coder:32b',
    displayName: 'Qwen 2.5 Coder (32B)',
    family: 'qwen-coder',
    sizeBytesApprox: '20.0 GB',
    description: 'Premier 32B coding model rivaling proprietary models — requires 32GB+ VRAM for a safe budget',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-r1:32b',
    displayName: 'DeepSeek R1 Distill Qwen (32B)',
    family: 'deepseek-r1',
    sizeBytesApprox: '20.0 GB',
    description: 'Ultra-scale 32B reasoning model for exhaustive multi-file code synthesis',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-coder-v2:16b-lite-instruct-q4_k_m',
    displayName: 'DeepSeek Coder V2 Lite (16B Q4_K_M)',
    family: 'deepseek',
    sizeBytesApprox: '8.9 GB',
    description: 'MoE code reasoning engine with 236 programming languages support',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-coder:6.7b',
    displayName: 'DeepSeek Coder (6.7B)',
    family: 'deepseek',
    sizeBytesApprox: '3.8 GB',
    description: 'Specialized coding model for entry-level GPU hardware with 8GB or more VRAM',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5-coder:3b',
    displayName: 'Qwen 2.5 Coder (3B)',
    family: 'qwen-coder',
    sizeBytesApprox: '1.9 GB',
    description: 'Compact code model for low-VRAM devices with rapid reasoning',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-r1:8b',
    displayName: 'DeepSeek R1 Distill (8B)',
    family: 'deepseek-r1',
    sizeBytesApprox: '4.9 GB',
    description: 'Distilled 8B reasoning model for 12GB+ GPUs',
    recommendedForProfiles: [],
  },
  {
    modelName: 'phi4:14b',
    displayName: 'Microsoft Phi-4 (14B)',
    family: 'phi',
    sizeBytesApprox: '9.1 GB',
    description: 'Microsoft state-of-the-art synthetic reasoning & algorithmic assistant',
    recommendedForProfiles: [],
  },
  {
    modelName: 'phi4-mini:3.8b',
    displayName: 'Microsoft Phi-4 Mini (3.8B)',
    family: 'phi',
    sizeBytesApprox: '2.5 GB',
    description: 'Compact Microsoft reasoning model with function calling for low-VRAM hosts',
    recommendedForProfiles: [],
  },
  {
    modelName: 'codestral:22b-v0.1-q4_k_m',
    displayName: 'Mistral Codestral (22B Q4_K_M)',
    family: 'mistral',
    sizeBytesApprox: '13.0 GB',
    description: 'High-capacity code intelligence engine for complex software design',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:30b-a3b',
    displayName: 'Qwen 3 (30B A3B MoE)',
    family: 'qwen',
    sizeBytesApprox: '18.6 GB',
    description: 'Current-generation MoE reasoning model: 30B knowledge at ~3B active-parameter speed',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:32b',
    displayName: 'Qwen 3 (32B)',
    family: 'qwen',
    sizeBytesApprox: '20.0 GB',
    description: 'Current-generation dense 32B reasoning engine for 32GB+ workstations',
    recommendedForProfiles: [],
  },
]

// ⚡ Large coding models (14B+) for complex multi-file work. Requires 12GB+ VRAM, or hybrid
// system-RAM offloading.
export const LARGE_CODING_CATALOG: RawModelCatalogEntry[] = [
  {
    modelName: 'qwen2.5-coder:14b',
    displayName: 'Qwen 2.5 Coder (14B)',
    family: 'qwen-coder',
    sizeBytesApprox: '9.0 GB',
    description: 'Large-scale coding intelligence for complex multi-file refactoring and architecture tasks (12GB+ VRAM)',
    recommendedForProfiles: ['highend'],
  },
  {
    modelName: 'qwen2.5-coder:14b-instruct-q4_k_m',
    displayName: 'Qwen 2.5 Coder (14B Q4_K_M)',
    family: 'qwen-coder',
    sizeBytesApprox: '8.9 GB',
    description: 'Quantized 14B heavy escalation model with reduced VRAM footprint on 12GB GPUs',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:14b',
    displayName: 'Qwen 3 (14B)',
    family: 'qwen',
    sizeBytesApprox: '9.3 GB',
    description: 'Current-generation 14B escalation target with explicit thinking mode for failed tool loops',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-r1:14b',
    displayName: 'DeepSeek R1 Distill Qwen (14B)',
    family: 'deepseek-r1',
    sizeBytesApprox: '9.2 GB',
    description: 'High-capacity 14B Qwen-distilled chain-of-thought reasoning engine for escalated debugging',
    recommendedForProfiles: [],
  },
  {
    modelName: 'deepseek-r1:14b-qwen-distill-q4_k_m',
    displayName: 'DeepSeek R1 Distill Qwen (14B Q4_K_M)',
    family: 'deepseek-r1',
    sizeBytesApprox: '9.0 GB',
    description: 'Quantized heavy reasoning model for auto-healing tool loop escalation on 12GB GPUs',
    recommendedForProfiles: [],
  },
  {
    modelName: 'codestral:22b-v0.1-q4_k_m',
    displayName: 'Mistral Codestral (22B Q4_K_M)',
    family: 'mistral',
    sizeBytesApprox: '13.0 GB',
    description: 'Enterprise-grade Mistral code intelligence for exhaustive system-wide architecture refactors',
    recommendedForProfiles: ['extreme'],
  },
  {
    modelName: 'devstral:24b',
    displayName: 'Mistral Devstral (24B)',
    family: 'mistral',
    sizeBytesApprox: '14.0 GB',
    description: 'Agentic coding model built for long tool-calling trajectories over large codebases',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gpt-oss:20b',
    displayName: 'GPT-OSS (20B)',
    family: 'gpt-oss',
    sizeBytesApprox: '13.5 GB',
    description: 'Open-weight reasoning model with configurable effort for escalated auto-healing turns',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3-coder:30b',
    displayName: 'Qwen 3 Coder (30B A3B MoE)',
    family: 'qwen-coder',
    sizeBytesApprox: '18.6 GB',
    description: 'MoE escalation target: 30B-class coding accuracy at 3B active-parameter throughput',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5-coder:32b',
    displayName: 'Qwen 2.5 Coder (32B)',
    family: 'qwen-coder',
    sizeBytesApprox: '20.0 GB',
    description: 'Premier 32B coding model rivaling proprietary models — requires 32GB+ VRAM workstation',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5-coder:32b-instruct-q4_k_m',
    displayName: 'Qwen 2.5 Coder (32B Q4_K_M)',
    family: 'qwen-coder',
    sizeBytesApprox: '19.5 GB',
    description: 'Quantized 32B coding model for extreme workstations and multi-GPU setups',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:30b-a3b',
    displayName: 'Qwen 3 (30B A3B MoE)',
    family: 'qwen',
    sizeBytesApprox: '18.6 GB',
    description: 'MoE escalation target with strong reasoning at 3B active-parameter throughput',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:32b',
    displayName: 'Qwen 3 (32B)',
    family: 'qwen',
    sizeBytesApprox: '20.0 GB',
    description: 'Dense 32B escalation target for exhaustive multi-file reasoning on 32GB+ workstations',
    recommendedForProfiles: [],
  },
]

// 💬 General / RAG Chat Models
export const CHAT_TIER_CATALOG: RawModelCatalogEntry[] = [
  {
    modelName: 'llama3.2:3b',
    displayName: 'Llama 3.2 (3B)',
    family: 'llama',
    sizeBytesApprox: '2.0 GB',
    description: 'Fast responsive conversational assistant for low-spec, 8GB GPUs or CPU systems',
    recommendedForProfiles: ['legacy', 'entry', 'midrange'],
  },
  {
    modelName: 'llama3.2:1b',
    displayName: 'Llama 3.2 (1B)',
    family: 'llama',
    sizeBytesApprox: '1.3 GB',
    description: 'Smallest conversational model for minimum hardware with 8GB RAM or less',
    recommendedForProfiles: [],
  },
  {
    modelName: 'llama3.1:8b',
    displayName: 'Llama 3.1 (8B)',
    family: 'llama',
    sizeBytesApprox: '4.9 GB',
    description: 'Meta 8B balanced conversational assistant for 12GB+ GPUs and multi-document RAG',
    recommendedForProfiles: ['highend', 'extreme'],
  },
  {
    modelName: 'qwen3:4b',
    displayName: 'Qwen 3 (4B)',
    family: 'qwen',
    sizeBytesApprox: '2.6 GB',
    description: 'Current-generation compact assistant with strong multilingual factual recall',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:8b',
    displayName: 'Qwen 3 (8B)',
    family: 'qwen',
    sizeBytesApprox: '5.2 GB',
    description: 'Current-generation 8B conversational model for grounded multi-document RAG',
    recommendedForProfiles: [],
  },
  {
    modelName: 'granite3.3:2b',
    displayName: 'IBM Granite 3.3 (2B)',
    family: 'granite',
    sizeBytesApprox: '1.5 GB',
    description: 'IBM compact long-context model well suited to citation-faithful RAG answers',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5:7b',
    displayName: 'Qwen 2.5 (7B)',
    family: 'qwen',
    sizeBytesApprox: '4.7 GB',
    description: 'High-intelligence multilingual conversational model with strong factual recall',
    recommendedForProfiles: [],
  },
  {
    modelName: 'mistral:7b',
    displayName: 'Mistral (7B)',
    family: 'mistral',
    sizeBytesApprox: '4.1 GB',
    description: 'High-speed instruction model for RAG and factual Q&A',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gemma3:4b',
    displayName: 'Google Gemma 3 (4B)',
    family: 'gemma',
    sizeBytesApprox: '3.3 GB',
    description: 'Google Gemma 3 compact assistant with 128k context and broad language coverage',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gemma3:12b',
    displayName: 'Google Gemma 3 (12B)',
    family: 'gemma',
    sizeBytesApprox: '8.1 GB',
    description: 'Google Gemma 3 high-precision conversational assistant for 12GB+ GPUs',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gemma2:9b',
    displayName: 'Gemma 2 (9B)',
    family: 'gemma',
    sizeBytesApprox: '5.5 GB',
    description: 'Google Gemma 2 high-precision conversational assistant',
    recommendedForProfiles: [],
  },
  {
    modelName: 'glm4:9b',
    displayName: 'Zhipu GLM-4 (9B)',
    family: 'glm',
    sizeBytesApprox: '5.5 GB',
    description: 'Zhipu high-accuracy bilingual (EN/ZH) conversational model for grounded RAG',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5:32b',
    displayName: 'Qwen 2.5 (32B)',
    family: 'qwen',
    sizeBytesApprox: '20.0 GB',
    description: 'Large-scale multilingual conversational model for 32GB+ workstations',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gemma3:27b',
    displayName: 'Google Gemma 3 (27B)',
    family: 'gemma',
    sizeBytesApprox: '17.0 GB',
    description: 'Google flagship Gemma 3 conversational assistant for extreme workstations',
    recommendedForProfiles: [],
  },
  {
    modelName: 'mixtral:8x7b',
    displayName: 'Mixtral (8x7B MoE)',
    family: 'mistral',
    sizeBytesApprox: '26.0 GB',
    description: 'Mistral Mixture-of-Experts model with strong multi-document reasoning for 32GB+ hosts',
    recommendedForProfiles: [],
  },
  {
    modelName: 'llama3.3:70b',
    displayName: 'Llama 3.3 (70B)',
    family: 'llama',
    sizeBytesApprox: '40.0 GB',
    description: 'Meta flagship conversational model rivaling 3.1 405B — requires a 48GB+ workstation',
    recommendedForProfiles: [],
  },
]

// 🌐 Document Translation Models
export const TRANSLATION_TIER_CATALOG: RawModelCatalogEntry[] = [
  {
    modelName: 'qwen2.5:3b',
    displayName: 'Qwen 2.5 (3B)',
    family: 'qwen',
    sizeBytesApprox: '1.9 GB',
    description: 'High-efficiency multilingual translation preserving layout without VRAM pressure',
    recommendedForProfiles: ['midrange'],
  },
  {
    modelName: 'qwen2.5:1.5b',
    displayName: 'Qwen 2.5 (1.5B)',
    family: 'qwen',
    sizeBytesApprox: '1.0 GB',
    description: 'Lightweight multilingual translation engine for CPU & entry-level GPU systems',
    recommendedForProfiles: ['legacy', 'entry'],
  },
  {
    modelName: 'qwen2.5:7b',
    displayName: 'Qwen 2.5 (7B)',
    family: 'qwen',
    sizeBytesApprox: '4.7 GB',
    description: 'Premier multilingual translation engine for 12GB+ GPUs preserving format',
    recommendedForProfiles: ['highend'],
  },
  {
    modelName: 'qwen3:4b',
    displayName: 'Qwen 3 (4B)',
    family: 'qwen',
    sizeBytesApprox: '2.6 GB',
    description: 'Current-generation compact translator with wide language coverage for low-VRAM hosts',
    recommendedForProfiles: [],
  },
  {
    modelName: 'aya-expanse:8b',
    displayName: 'Aya Expanse (8B)',
    family: 'cohere',
    sizeBytesApprox: '5.1 GB',
    description: 'Cohere highly-aligned multilingual translation and cross-lingual model',
    recommendedForProfiles: ['extreme'],
  },
  {
    modelName: 'gemma3:4b',
    displayName: 'Google Gemma 3 (4B)',
    family: 'gemma',
    sizeBytesApprox: '3.3 GB',
    description: 'Google Gemma 3 multilingual model covering 140+ languages for document translation',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gemma2:2b',
    displayName: 'Google Gemma 2 (2B)',
    family: 'gemma',
    sizeBytesApprox: '1.6 GB',
    description: 'Ultra-lightweight fast multilingual translation model for low-spec systems',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gemma2:9b',
    displayName: 'Google Gemma 2 (9B)',
    family: 'gemma',
    sizeBytesApprox: '5.5 GB',
    description: 'High-fidelity multilingual translation model for complex documents',
    recommendedForProfiles: [],
  },
  {
    modelName: 'mistral:7b',
    displayName: 'Mistral (7B)',
    family: 'mistral',
    sizeBytesApprox: '4.1 GB',
    description: 'European high-speed instruction model for document translation',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen3:14b',
    displayName: 'Qwen 3 (14B)',
    family: 'qwen',
    sizeBytesApprox: '9.3 GB',
    description: 'Current-generation 14B translator with strong multilingual layout preservation',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gemma3:27b',
    displayName: 'Google Gemma 3 (27B)',
    family: 'gemma',
    sizeBytesApprox: '17.0 GB',
    description: 'Google flagship Gemma 3 multilingual translator for extreme workstations',
    recommendedForProfiles: [],
  },
]

// 👁️ Vision Tier Recommendations
export const VISION_TIER_CATALOG: RawModelCatalogEntry[] = [
  {
    modelName: 'moondream:latest',
    displayName: 'Moondream 2 (1.8B)',
    family: 'moondream',
    sizeBytesApprox: '1.7 GB',
    description: 'Compact fast vision model with minimal footprint for CPU, 4GB and 8GB GPU hardware',
    recommendedForProfiles: ['legacy', 'entry', 'midrange'],
  },
  {
    modelName: 'llava:7b',
    displayName: 'LLaVA (7B)',
    family: 'llava',
    sizeBytesApprox: '4.5 GB',
    description: 'Standard vision-language assistant model for general image & OCR inspection on 12GB+ GPUs',
    recommendedForProfiles: ['highend'],
  },
  {
    modelName: 'llama3.2-vision:11b',
    displayName: 'Llama 3.2 Vision (11B)',
    family: 'llama-vision',
    sizeBytesApprox: '7.9 GB',
    description: 'Meta multimodal model for diagram, table & page layout OCR/inspection',
    recommendedForProfiles: ['extreme'],
  },
  {
    modelName: 'qwen2.5vl:3b',
    displayName: 'Qwen 2.5 VL (3B)',
    family: 'qwen-vl',
    sizeBytesApprox: '3.2 GB',
    description: 'Compact current-generation vision model with strong document and table OCR accuracy',
    recommendedForProfiles: [],
  },
  {
    modelName: 'qwen2.5vl:7b',
    displayName: 'Qwen 2.5 VL (7B)',
    family: 'qwen-vl',
    sizeBytesApprox: '6.0 GB',
    description: 'Current-generation vision model for dense page layout, chart and handwriting extraction',
    recommendedForProfiles: [],
  },
  {
    modelName: 'gemma3:4b',
    displayName: 'Google Gemma 3 (4B Vision)',
    family: 'gemma',
    sizeBytesApprox: '3.3 GB',
    description: 'Google Gemma 3 multimodal variant for combined image understanding and text extraction',
    recommendedForProfiles: [],
  },
  {
    modelName: 'minicpm-v:8b',
    displayName: 'MiniCPM-V (8B)',
    family: 'minicpm',
    sizeBytesApprox: '5.5 GB',
    description: 'High-efficiency multimodal OCR & document layout vision model',
    recommendedForProfiles: [],
  },
]

// 🧠 Vector Embedding Tier Recommendations
export const EMBEDDING_TIER_CATALOG: RawModelCatalogEntry[] = [
  {
    modelName: 'nomic-embed-text:latest',
    displayName: 'Nomic Embed Text (768-dim)',
    family: 'nomic',
    sizeBytesApprox: '274 MB',
    description: 'Standard high-recall embedding model for LanceDB vector search',
    recommendedForProfiles: ['legacy', 'entry', 'midrange'],
  },
  {
    modelName: 'bge-m3:latest',
    displayName: 'BAAI BGE-M3 (Multilingual 1024d)',
    family: 'bge',
    sizeBytesApprox: '1.1 GB',
    description: 'Multilingual dense & sparse embedding model for enterprise search',
    recommendedForProfiles: ['highend', 'extreme'],
  },
  {
    modelName: 'embeddinggemma:300m',
    displayName: 'Google EmbeddingGemma (768d)',
    family: 'gemma',
    sizeBytesApprox: '620 MB',
    description: 'Google compact multilingual embedding model tuned for on-device retrieval',
    recommendedForProfiles: [],
  },
  {
    modelName: 'granite-embedding:278m',
    displayName: 'IBM Granite Embedding (768d)',
    family: 'granite',
    sizeBytesApprox: '560 MB',
    description: 'IBM multilingual retrieval embedding model with permissive enterprise licensing',
    recommendedForProfiles: [],
  },
  {
    modelName: 'snowflake-arctic-embed:latest',
    displayName: 'Snowflake Arctic Embed (1024d)',
    family: 'snowflake',
    sizeBytesApprox: '600 MB',
    description: 'High-density multi-lingual retrieval embedding model',
    recommendedForProfiles: [],
  },
  {
    modelName: 'mxbai-embed-large:latest',
    displayName: 'MixedBread mxbai-embed-large',
    family: 'mxbai',
    sizeBytesApprox: '670 MB',
    description: 'Large high-density vector embedding model',
    recommendedForProfiles: [],
  },
  {
    modelName: 'all-minilm:latest',
    displayName: 'All-MiniLM-L6-v2',
    family: 'minilm',
    sizeBytesApprox: '120 MB',
    description: 'Ultra-fast compact sentence embedding model for lightweight CPU systems',
    recommendedForProfiles: [],
  },
]

// 🏥 Medical & Healthcare Domain Models
export const MEDICAL_TIER_CATALOG: RawModelCatalogEntry[] = [
  {
    modelName: 'llama3.2:3b',
    displayName: 'Llama 3.2 (3B)',
    family: 'llama',
    sizeBytesApprox: '2.0 GB',
    description: 'Lightweight biomedical and clinical terminology assistant for 4GB-8GB GPUs',
    recommendedForProfiles: ['legacy', 'entry', 'midrange'],
  },
  {
    modelName: 'adrienbrault/biomistral-7b:Q4_K_M',
    displayName: 'BioMistral (7B Q4_K_M)',
    family: 'biomistral',
    sizeBytesApprox: '4.1 GB',
    description: 'Specialized biomedical QA, clinical pharmacology & PubMed evidence for 12GB+ GPUs',
    recommendedForProfiles: ['highend', 'extreme'],
  },
  {
    modelName: 'meditron:7b',
    displayName: 'Meditron (7B)',
    family: 'meditron',
    sizeBytesApprox: '4.3 GB',
    description: 'Clinical guidelines, PubMed evidence & medical Q&A assistant',
    recommendedForProfiles: [],
  },
  {
    modelName: 'meditron:70b',
    displayName: 'Meditron (70B)',
    family: 'meditron',
    sizeBytesApprox: '40.0 GB',
    description: 'Enterprise clinical decision support — requires a 48GB+ multi-GPU workstation',
    recommendedForProfiles: [],
  },
  {
    modelName: 'llama3.1:8b',
    displayName: 'Llama 3.1 (8B)',
    family: 'llama',
    sizeBytesApprox: '4.9 GB',
    description: 'Meta 8B balanced model with broad medical and clinical terminology support',
    recommendedForProfiles: [],
  },
]

// ⚖️ Legal & Compliance Domain Models
export const LEGAL_TIER_CATALOG: RawModelCatalogEntry[] = [
  {
    modelName: 'llama3.2:3b',
    displayName: 'Llama 3.2 (3B)',
    family: 'llama',
    sizeBytesApprox: '2.0 GB',
    description: 'Lightweight legal contract review & compliance for low-VRAM & 8GB systems',
    recommendedForProfiles: ['legacy', 'entry', 'midrange'],
  },
  {
    modelName: 'llama3.1:8b',
    displayName: 'Llama 3.1 (8B)',
    family: 'llama',
    sizeBytesApprox: '4.9 GB',
    description: 'Statutory compliance, legal drafting & regulatory entity extraction for 12GB+ GPUs',
    recommendedForProfiles: ['highend'],
  },
  {
    modelName: 'command-r7b:latest',
    displayName: 'Cohere Command R7B',
    family: 'cohere',
    sizeBytesApprox: '5.1 GB',
    description: 'Cohere grounded RAG with strict citations, compact enough for 12GB GPUs',
    recommendedForProfiles: [],
  },
  {
    modelName: 'mistral-small3.2:24b',
    displayName: 'Mistral Small 3.2 (24B)',
    family: 'mistral',
    sizeBytesApprox: '14.0 GB',
    description: 'Long-context 24B model for statutory synthesis and contract risk review on 24GB GPUs',
    recommendedForProfiles: ['extreme'],
  },
  {
    modelName: 'mistral:7b',
    displayName: 'Mistral (7B)',
    family: 'mistral',
    sizeBytesApprox: '4.1 GB',
    description: 'Specialized legal analysis, European jurisprudence & contract clause review',
    recommendedForProfiles: [],
  },
  {
    modelName: 'command-r:35b',
    displayName: 'Cohere Command R (35B)',
    family: 'cohere',
    sizeBytesApprox: '20.0 GB',
    description: 'Grounded RAG with strict citations — requires 32GB+ VRAM for a safe budget',
    recommendedForProfiles: [],
  },
  {
    modelName: 'command-r-plus:104b',
    displayName: 'Cohere Command R+ (104B)',
    family: 'cohere',
    sizeBytesApprox: '60.0 GB',
    description: 'Enterprise legal corpus reasoning, high-precision compliance and contract risk',
    recommendedForProfiles: [],
  },
]

/**
 * Parses the human-readable `sizeBytesApprox` label into GB. The catalog is deliberately
 * self-describing so this module stays dependency-free: importing `estimateModelWeightGB`
 * from hardwareRecommendationEngine.ts would create a cycle, since that module consumes
 * every catalog above. The engine test asserts the two never drift apart.
 */
export function parseCatalogSizeGB(sizeBytesApprox: string): number {
  const match = (sizeBytesApprox || '').trim().match(/^([\d.]+)\s*(GB|MB)$/i)
  if (!match) return Number.POSITIVE_INFINITY
  const value = parseFloat(match[1])
  if (!isFinite(value) || value <= 0) return Number.POSITIVE_INFINITY
  return match[2].toUpperCase() === 'MB' ? value / 1024 : value
}


